---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{.WWW_REF_NAME}}-service
  name: {{.WWW_REF_NAME}}-service
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8443
  selector:
    name: {{.WWW_REF_NAME}}
