name: Publish Docker
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 11 * * 1' # Weekly on Mondays at 11:00
jobs:
  test-ui-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        working-directory: ./server
        run: chmod +x gradlew
      - name: Run tests
        working-directory: ./server
        run: ./gradlew clean test

  test-react-ui:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ./client
        run: npm install
      - name: Run tests with coverage
        working-directory: ./client
        run: npm run test-coverage
        env:
          CI: true

  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: 'reference-data-service'
      IMAGE_DOCKER_HUB: 'ukhomeofficedigital/reference-data-service'
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE }}:latest
      - name: Publish to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ env.IMAGE_DOCKER_HUB }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: quay.io
          cache: true
          snapshot: true
          tags: "${{ github.sha }}"
